export const catalogoVinos = [

{
    nombre: 'Corona de Aragon Crianza',
    tipo: 'tintos',
    litros: '750 ML',
    imagen: 'assets/wines/Corona-de-Aragon-Crianza.jpg',
    precioUnitario: '5,900',
    precioCaja: '35,400',
    cantidadCaja: '6',
    paisOrigen: 'España, Cariñena',
    bodegasOrigen: 'Grandes Vinos',
},
{
    nombre: 'Corona de Aragon Reserva',
    tipo: 'tintos',
    litros: '750 ML',
    imagen: 'assets/wines/Corona-de-Aragon-Reserva.jpg',
    precioUnitario: '7,500',
    precioCaja: '45,000',
    cantidadCaja: '6',
    paisOrigen: 'España, Cariñena',
    bodegasOrigen: 'Grandes Vinos',
},

{
    nombre: 'Castillo Monte La Reina Crianza',
    tipo: 'tintos',
    litros: '750 ML',
    imagen: '',
    precioUnitario: '8,500',
    precioCaja: '51,000',
    cantidadCaja: '6',
    paisOrigen: 'España, Toro',
    bodegasOrigen: 'Castillo Monte la Reina',
},

{
    nombre: 'Castillo Monte La Reina Joven',
    tipo: 'tintos',
    litros: '750 ML',
    imagen: 'assets/wines/Castillo-Monte-la-Reina-Joven.jpg',
    precioUnitario: '3,800',
    precioCaja: '22,800',
    cantidadCaja: '6',
    paisOrigen: 'España, Toro',
    bodegasOrigen: 'Castillo Monte la Reina',
},


{
    nombre: 'IGLUP Vino Blanco',
    tipo: 'blancos',
    litros: '200 ML',
    imagen: 'assets/wines/Iglup-White.jpg',
    precioUnitario: '950',
    precioCaja: '5,700',
    cantidadCaja: '6',
    paisOrigen: 'España, Cariñena',
    bodegasOrigen: 'Grandes Vinos',
},
{
    nombre: 'IGLUP Vino Rosado',
    tipo: 'rosados',
    litros: '200 ML',
    imagen: 'assets/wines/Iglup-Rose.jpg',
    precioUnitario: '950',
    precioCaja: '5,700',
    cantidadCaja: '6',
    paisOrigen: 'España, Cariñena',
    bodegasOrigen: 'Grandes Vinos',
},

]

export const catalogoRon = [{
    nombre: 'Ron Blanco ISSI',
    tipo: 'ron',
    litros: '1000 ML',
    imagen: 'assets/wines/Issi-Ron-Blanco-1L.jpg',
    precioUnitario: '4,800',
    precioCaja: '54,000',
    paisOrigen: '',
    cantidadCaja: '12',
    bodegasOrigen: 'Beveland, SA',
},
{
    nombre: 'Ron Dorado ISSI',
    tipo: 'ron',
    litros: '1000 ML',
    imagen: 'assets/wines/Ron-Dorado-ISSI-1L.jpg',
    precioUnitario: '4,800',
    precioCaja: '54,000',
    paisOrigen: '',
    cantidadCaja: '12',
    bodegasOrigen: 'Beveland, SA',
},
{
    nombre: 'Ron Marama Fiji Spiced',
    tipo: 'ron',
    litros: '700 ML',
    imagen: 'assets/wines/Ron-Marama-Fiji-Spiced-700ml.jpg',
    precioUnitario: '12,000',
    precioCaja: '46,000',
    paisOrigen: '',
    cantidadCaja: '4',
    bodegasOrigen: 'Beveland, SA',
},
{
    nombre: 'Ron Relicario Superior',
    tipo: 'ron',
    litros: '700 ML',
    imagen: 'assets/wines/Ron-Relicario-Superior-700ml.jpg',
    precioUnitario: '15,000',
    precioCaja: '64,000',
    paisOrigen: '',
    cantidadCaja: '4',
    bodegasOrigen: 'Beveland, SA',
},
{
    nombre: 'Ron Relicario Supremo',
    tipo: 'ron',
    litros: '700 ML',
    imagen: 'assets/wines/Ron-Relicario-Supremo-700ml.jpg',
    precioUnitario: '28,500',
    precioCaja: '114,000',
    paisOrigen: '',
    cantidadCaja: '4',
    bodegasOrigen: 'Beveland, SA',
},
]

export const catalogoVodka = [{
    nombre: 'Vodka Kzarrof',
    tipo: 'vodka',
    litros: '1000 ML',
    imagen: 'assets/wines/Vodka-Kzaroff.jpg',
    precioUnitario: '4,350',
    precioCaja: '44,400',
    paisOrigen: '',
    cantidadCaja: '12',
    bodegasOrigen: 'Beveland, SA',
},
{
    nombre: 'Vodka Krova',
    tipo: 'vodka',
    litros: '700 ML',
    imagen: 'assets/wines/Vodka-Krova.jpg',
    precioUnitario: '11,500',
    precioCaja: '43,500',
    paisOrigen: '',
    cantidadCaja: '3',
    bodegasOrigen: 'Beveland, SA',
},
]

export const catalogoGin = [{
    nombre: 'Ginebra Jodhpur',
    tipo: 'ginebra',
    litros: '700 ML',
    imagen: 'assets/wines/Ginebraa-Jodhpur.jpg',
    precioUnitario: '11,000',
    precioCaja: '44,000',
    paisOrigen: '',
    cantidadCaja: '4',
    bodegasOrigen: 'Beveland, SA',
},
{
    nombre: 'Ginebra Blimey',
    tipo: 'ginebra',
    litros: '1000 ML',
    imagen: 'assets/wines/Blimey-Dry-Gin.jpg',
    precioUnitario: '4,550',
    precioCaja: '54,600',
    paisOrigen: '',
    cantidadCaja: '12',
    bodegasOrigen: 'Beveland, SA',
},
]

export const catalogoTequila = [
    
    {
        nombre: 'Destilado de Agave ISSI',
        tipo: 'tequila',
        litros: '1000 ML',
        imagen: 'assets/wines/Agave-Blanco-Issi.jpg',
        precioUnitario: '7,500',
        precioCaja: '90,000',
        paisOrigen: '',
        cantidadCaja: '12',
        bodegasOrigen: 'Beveland SA',
    },
]

export const catalogoLicores = [{
    nombre: 'Licor de Mango BV Land',
    tipo: 'licor',
    litros: '700 ML',
    imagen: 'assets/wines/BV-Land-Mango.jpg',
    precioUnitario: '8,000',
    precioCaja: '48,000',
    paisOrigen: '',
    cantidadCaja: '6',
    bodegasOrigen: 'Beveland, SA',
},
{
    nombre: 'Licor de Almendras BV Land',
    tipo: 'licor',
    litros: '700 ML',
    imagen: 'assets/wines/BVLand-almendras.jpg',
    precioUnitario: '8,000',
    precioCaja: '48,000',
    paisOrigen: '',
    cantidadCaja: '6',
    bodegasOrigen: 'Beveland, SA',
},
{
    nombre: 'Licor de Melocotón BV Land',
    tipo: 'licor',
    litros: '700 ML',
    imagen: 'assets/wines/BVLand-almendras.jpg',
    precioUnitario: '8,000',
    precioCaja: '48,000',
    paisOrigen: '',
    cantidadCaja: '6',
    bodegasOrigen: 'Beveland, SA',
},
{
    nombre: 'Licor de Menta Verde DISCO/KAMEL',
    tipo: 'licor',
    litros: '1000 ML',
    imagen: 'assets/wines/Licor-Menta-Kamel.jpg',
    precioUnitario: '4,700',
    precioCaja: '56,400',
    paisOrigen: '',
    cantidadCaja: '12',
    bodegasOrigen: 'Deva, SA',
},
{
    nombre: 'Licor de Curaçao Blue KAMEL',
    tipo: 'licor',
    litros: '1000 ML',
    imagen: 'assets/wines/Licor-Curacao-KAMEL.png',
    precioUnitario: '4,700',
    precioCaja: '56,400',
    paisOrigen: '',
    cantidadCaja: '12',
    bodegasOrigen: 'Deva, SA',
},
{
    nombre: 'Licor Amaretto KAMEL',
    tipo: 'licor',
    litros: '1000 ML',
    imagen: 'assets/wines/Licor-Amaretto-KAMEL.png',
    precioUnitario: '4,700',
    precioCaja: '56,400',
    paisOrigen: '',
    cantidadCaja: '12',
    bodegasOrigen: 'Deva, SA',
},
{
    nombre: 'Licor de Manzana Verde DISCO/KAMEL',
    tipo: 'licor',
    litros: '1000 ML',
    imagen: 'assets/wines/Licor-de-Manzana-Disco.jpg',
    precioUnitario: '4,700',
    precioCaja: '56,400',
    paisOrigen: '',
    cantidadCaja: '12',
    bodegasOrigen: 'Deva, SA',
},
{
    nombre: 'Licor de Melón DISCO/KAMEL',
    tipo: 'licor',
    litros: '1000 ML',
    imagen: 'assets/wines/Licor-Melon-Kamel.jpg',
    precioUnitario: '4,700',
    precioCaja: '56,400',
    paisOrigen: '',
    cantidadCaja: '12',
    bodegasOrigen: 'Deva, SA',
},
{
    nombre: 'Licor de Café DISCO/KAMEL',
    tipo: 'licor',
    litros: '1000 ML',
    imagen: 'assets/wines/Licor-de-cafe-DISCO.jpg',
    precioUnitario: '4,700',
    precioCaja: '56,400',
    paisOrigen: '',
    cantidadCaja: '12',
    bodegasOrigen: 'Deva, SA',
},
{
    nombre: 'Licor de Almendra DISCO/KAMEL',
    tipo: 'licor',
    litros: '1000 ML',
    imagen: 'assets/wines/Licor-almendra-Disco-Baja.jpg',
    precioUnitario: '4,700',
    precioCaja: '56,400',
    paisOrigen: '',
    cantidadCaja: '12',
    bodegasOrigen: 'Deva, SA',
},
]