export const catalogoVinos = [{
    nombre: 'Vino Blanco La Terra',
    tipo: 'blancos',
    litros: '750 ML',
    imagen: 'assets/wines/La-Terra-Blanco.jpg',
    precioUnitario: '3,129',
    precioCaja: '37,548',
    cantidadCaja: '12',
    paisOrigen: 'España, Penedes',
    bodegasOrigen: 'Joan Sarda',
},
{
    nombre: 'Vino Tinto Borbones Semidulce',
    tipo: 'tintos',
    litros: '750 ML',
    imagen: 'assets/wines/Borbones-Tinto.jpg',
    precioUnitario: '2,782',
    precioCaja: '33,390',
    cantidadCaja: '12',
    paisOrigen: 'España, Penedes',
    bodegasOrigen: 'Joan Sarda',
},
{
    nombre: 'Sardá Reserva',
    tipo: 'tintos',
    litros: '750 ML',
    imagen: 'assets/wines/Sarda-Reserva.jpg',
    precioUnitario: '8,000',
    precioCaja: '48,000',
    cantidadCaja: '6',
    paisOrigen: 'España, Penedes',
    bodegasOrigen: 'Joan Sarda',
},
{
    nombre: 'Corona de Aragon Crianza',
    tipo: 'tintos',
    litros: '750 ML',
    imagen: 'assets/wines/Corona-de-Aragon-Crianza.jpg',
    precioUnitario: '5,900',
    precioCaja: '35,400',
    cantidadCaja: '6',
    paisOrigen: 'España, Cariñena',
    bodegasOrigen: 'Grandes Vinos',
},
{
    nombre: 'Corona de Aragon Reserva',
    tipo: 'tintos',
    litros: '750 ML',
    imagen: 'assets/wines/Corona-de-Aragon-Reserva.jpg',
    precioUnitario: '7,500',
    precioCaja: '45,000',
    cantidadCaja: '6',
    paisOrigen: 'España, Cariñena',
    bodegasOrigen: 'Grandes Vinos',
},
{
    nombre: 'Castillo Monte La Reina Cuveé Privee',
    tipo: 'tintos',
    litros: '750 ML',
    imagen: 'assets/wines/Castillo-Monte-la-Reina-Cuvee-Privee.jpg',
    precioUnitario: '16,000',
    precioCaja: '96,000',
    cantidadCaja: '6',
    paisOrigen: 'España, Toro',
    bodegasOrigen: 'Castillo Monte la Reina',
},
{
    nombre: 'Castillo Monte La Reina Crianza',
    tipo: 'tintos',
    litros: '750 ML',
    imagen: '',
    precioUnitario: '8,500',
    precioCaja: '51,000',
    cantidadCaja: '6',
    paisOrigen: 'España, Toro',
    bodegasOrigen: 'Castillo Monte la Reina',
},
{
    nombre: 'Castillo Monte La Reina Roble',
    tipo: 'tintos',
    litros: '750 ML',
    imagen: 'assets/wines/Castillo-Monte-la-Reina-Roble.jpg',
    precioUnitario: '5,500',
    precioCaja: '33,000',
    cantidadCaja: '6',
    paisOrigen: 'España, Toro',
    bodegasOrigen: 'Castillo Monte la Reina',
},
{
    nombre: 'Castillo Monte La Reina Joven',
    tipo: 'tintos',
    litros: '750 ML',
    imagen: 'assets/wines/Castillo-Monte-la-Reina-Joven.jpg',
    precioUnitario: '3,800',
    precioCaja: '22,800',
    cantidadCaja: '6',
    paisOrigen: 'España, Toro',
    bodegasOrigen: 'Castillo Monte la Reina',
},
{
    nombre: 'Monte Ory Tempranillo-Merlot',
    tipo: 'tintos',
    litros: '750 ML',
    imagen: 'assets/wines/Monte-Ory-Tempranillo-Merlot.jpg',
    precioUnitario: '3,400',
    precioCaja: '20,400',
    cantidadCaja: '6',
    paisOrigen: 'España, Navarra',
    bodegasOrigen: 'Bodegas Manzanos',
},
{
    nombre: 'Monte Ory Crianza',
    tipo: 'tintos',
    litros: '750 ML',
    imagen: 'assets/wines/Monte-Ory-Crianza.jpg',
    precioUnitario: '4,500',
    precioCaja: '27,000',
    cantidadCaja: '6',
    paisOrigen: 'España, Navarra',
    bodegasOrigen: 'Bodegas Manzanos',
},
{
    nombre: 'Mas de Victor Tempranillo',
    tipo: 'tintos',
    litros: '750 ML',
    imagen: 'assets/wines/Mas-de-victor-Tempranillo.jpg',
    precioUnitario: '5,000',
    precioCaja: '60,000',
    cantidadCaja: '12',
    paisOrigen: 'España, Rioja',
    bodegasOrigen: 'Bodegas Manzanos',
},
{
    nombre: 'Mas de Victor Graciano',
    tipo: 'tintos',
    litros: '750 ML',
    imagen: 'assets/wines/Mas-de-victor-Graciano.jpg',
    precioUnitario: '5,000',
    precioCaja: '60,000',
    cantidadCaja: '12',
    paisOrigen: 'España, Rioja',
    bodegasOrigen: 'Bodegas Manzanos',
},
{
    nombre: 'Mas de Victor Crianza',
    tipo: 'tintos',
    litros: '750 ML',
    imagen: 'assets/wines/Mas-de-victor-Crianza.jpg',
    precioUnitario: '6,500',
    precioCaja: '78,000',
    cantidadCaja: '12',
    paisOrigen: 'España, Rioja',
    bodegasOrigen: 'Bodegas Manzanos',
},
{
    nombre: 'Mas de Victor Reserva',
    tipo: 'tintos',
    litros: '750 ML',
    imagen: 'assets/wines/Mas-de-victor-Reserva.jpg',
    precioUnitario: '11,500',
    precioCaja: '138,000',
    cantidadCaja: '12',
    paisOrigen: 'España, Rioja',
    bodegasOrigen: 'Bodegas Manzanos',
},
{
    nombre: 'IGLUP Vino Blanco',
    tipo: 'blancos',
    litros: '200 ML',
    imagen: 'assets/wines/Iglup-White.jpg',
    precioUnitario: '950',
    precioCaja: '5,700',
    cantidadCaja: '6',
    paisOrigen: 'España, Cariñena',
    bodegasOrigen: 'Grandes Vinos',
},
{
    nombre: 'IGLUP Vino Rosado',
    tipo: 'rosados',
    litros: '200 ML',
    imagen: 'assets/wines/Iglup-Rose.jpg',
    precioUnitario: '950',
    precioCaja: '5,700',
    cantidadCaja: '6',
    paisOrigen: 'España, Cariñena',
    bodegasOrigen: 'Grandes Vinos',
},
{
    nombre: 'Cava Castell de Ribes Semiseco',
    tipo: 'blancos',
    litros: '750 ML',
    imagen: 'assets/wines/Cava-Castell-Ribes-Semi-Seco.jpg',
    precioUnitario: '8,295',
    precioCaja: '49,770',
    cantidadCaja: '6',
    paisOrigen: 'España, Penedes',
    bodegasOrigen: 'Joan Sarda',
},
{
    nombre: 'Vino Tinto La Heredada Tempranillo',
    tipo: 'tintos',
    litros: '5000 ML',
    imagen: 'assets/wines/La-heredada-vino-tinto.jpg',
    precioUnitario: '10,590',
    precioCaja: '31,770',
    cantidadCaja: '3',
    paisOrigen: 'España, Navarra',
    bodegasOrigen: 'Bodegas Manzanos',
},
{
    nombre: 'Vino Rosado La Heredada Tempranillo',
    tipo: 'rosados',
    litros: '5000 ML',
    imagen: 'assets/wines/La-Heredada-Vino-Rosado.jpg',
    precioUnitario: '10,590',
    precioCaja: '31,770',
    cantidadCaja: '3',
    paisOrigen: 'España, Navarra',
    bodegasOrigen: 'Bodegas Manzanos',
},
{
    nombre: 'Vino Blanco La Heredada Viura',
    tipo: 'blancos',
    litros: '5000 ML',
    imagen: 'assets/wines/La-heredada-Vino-Blanco.jpg',
    precioUnitario: '10,590',
    precioCaja: '31,770',
    cantidadCaja: '3',
    paisOrigen: 'España, Navarra',
    bodegasOrigen: 'Bodegas Manzanos',
},
{
    nombre: 'Vino Tinto RUMBO Carbenet Sauvignon',
    tipo: 'tintos',
    litros: '750 ML',
    imagen: 'assets/wines/Vino-Tinto-RUMBO-Cabernet-Sauvignon.jpg',
    precioUnitario: '2,700',
    precioCaja: '32,400',
    cantidadCaja: '12',
    paisOrigen: 'Chile, Valle Central',
    bodegasOrigen: 'Bodega Terrapura',
},
{
    nombre: 'Vino Tinto RUMBO Merlot',
    tipo: 'tintos',
    litros: '750 ML',
    imagen: 'assets/wines/Vino-Tinto-RUMBO-Merlot.jpg',
    precioUnitario: '2,700',
    precioCaja: '32,400',
    cantidadCaja: '12',
    paisOrigen: 'Chile, Valle Central',
    bodegasOrigen: 'Bodega Terrapura',
},
{
    nombre: 'Vino Blanco RUMBO Sauvignon Blanc',
    tipo: 'blancos',
    litros: '750 ML',
    imagen: '',
    precioUnitario: '2,700',
    precioCaja: '32,400',
    cantidadCaja: '12',
    paisOrigen: 'Chile, Valle Central',
    bodegasOrigen: 'Bodega Terrapura',
},
{
    nombre: 'Vino Blanco RUMBO Chardonnay',
    tipo: 'blancos',
    litros: '750 ML',
    imagen: '',
    precioUnitario: '2,700',
    precioCaja: '32,400',
    cantidadCaja: '12',
    paisOrigen: 'Chile, Valle Central',
    bodegasOrigen: 'Bodega Terrapura',
},
]

export const catalogoRon = [{
    nombre: 'Ron Blanco ISSI',
    tipo: 'ron',
    litros: '1000 ML',
    imagen: 'assets/wines/Issi-Ron-Blanco-1L.jpg',
    precioUnitario: '4,800',
    precioCaja: '54,000',
    paisOrigen: '',
    cantidadCaja: '12',
    bodegasOrigen: 'Beveland, SA',
},
{
    nombre: 'Ron Dorado ISSI',
    tipo: 'ron',
    litros: '1000 ML',
    imagen: 'assets/wines/Ron-Dorado-ISSI-1L.jpg',
    precioUnitario: '4,800',
    precioCaja: '54,000',
    paisOrigen: '',
    cantidadCaja: '12',
    bodegasOrigen: 'Beveland, SA',
},
{
    nombre: 'Ron Marama Fiji Spiced',
    tipo: 'ron',
    litros: '700 ML',
    imagen: 'assets/wines/Ron-Marama-Fiji-Spiced-700ml.jpg',
    precioUnitario: '12,000',
    precioCaja: '46,000',
    paisOrigen: '',
    cantidadCaja: '4',
    bodegasOrigen: 'Beveland, SA',
},
{
    nombre: 'Ron Relicario Superior',
    tipo: 'ron',
    litros: '700 ML',
    imagen: 'assets/wines/Ron-Relicario-Superior-700ml.jpg',
    precioUnitario: '15,000',
    precioCaja: '64,000',
    paisOrigen: '',
    cantidadCaja: '4',
    bodegasOrigen: 'Beveland, SA',
},
{
    nombre: 'Ron Relicario Supremo',
    tipo: 'ron',
    litros: '700 ML',
    imagen: 'assets/wines/Ron-Relicario-Supremo-700ml.jpg',
    precioUnitario: '28,500',
    precioCaja: '114,000',
    paisOrigen: '',
    cantidadCaja: '4',
    bodegasOrigen: 'Beveland, SA',
},
]

export const catalogoVodka = [{
    nombre: 'Vodka Kzarrof',
    tipo: 'vodka',
    litros: '1000 ML',
    imagen: 'assets/wines/Vodka-Kzaroff.jpg',
    precioUnitario: '4,500',
    precioCaja: '44,400',
    paisOrigen: '',
    cantidadCaja: '12',
    bodegasOrigen: 'Beveland, SA',
},
{
    nombre: 'Vodka Krova',
    tipo: 'vodka',
    litros: '700 ML',
    imagen: 'assets/wines/Vodka-Krova.jpg',
    precioUnitario: '11,500',
    precioCaja: '43,500',
    paisOrigen: '',
    cantidadCaja: '3',
    bodegasOrigen: 'Beveland, SA',
},
]

export const catalogoGin = [{
    nombre: 'Ginebra Jodhpur',
    tipo: 'ginebra',
    litros: '700 ML',
    imagen: 'assets/wines/Ginebraa-Jodhpur.jpg',
    precioUnitario: '15,000',
    precioCaja: '66,000',
    paisOrigen: '',
    cantidadCaja: '3',
    bodegasOrigen: 'Beveland, SA',
},
{
    nombre: 'Ginebra Blimey',
    tipo: 'ginebra',
    litros: '1000 ML',
    imagen: 'assets/wines/Blimey-Dry-Gin.jpg',
    precioUnitario: '4,800',
    precioCaja: '47,400',
    paisOrigen: '',
    cantidadCaja: '12',
    bodegasOrigen: 'Beveland, SA',
},
]

export const catalogoTequila = [{
    nombre: 'Tequila Jaliscience Blanco',
    tipo: 'tequila',
    litros: '1000 ML',
    imagen: 'assets/wines/Jaliscience-blanco-1l.jpg',
    precioUnitario: '8,700',
    precioCaja: '87,000',
    paisOrigen: '',
    cantidadCaja: '12',
    bodegasOrigen: 'Agroind Guadalajara',
},
{
    nombre: 'Tequila Jaliscience Oro',
    tipo: 'tequila',
    litros: '1000 ML',
    imagen: '',
    precioUnitario: '8,700',
    precioCaja: '87,000',
    paisOrigen: '',
    cantidadCaja: '12',
    bodegasOrigen: 'Agroind Guadalajara',
},
{
    nombre: 'Tequila Reposado Las Nuevas Trancas',
    tipo: 'tequila',
    litros: '750 ML',
    imagen: 'assets/wines/Las-trancas-reposado-750ml.jpg',
    precioUnitario: '9,000',
    precioCaja: '90,000',
    paisOrigen: '',
    cantidadCaja: '6',
    bodegasOrigen: 'Agroind Guadalajara',
},
{
    nombre: 'Tequila 30-30 Reposado',
    tipo: 'tequila',
    litros: '750 ML',
    imagen: 'assets/wines/3030-reposado-750ml.jpg',
    precioUnitario: '8,500',
    precioCaja: '18,000',
    paisOrigen: '',
    cantidadCaja: '12',
    bodegasOrigen: 'Agroind Guadalajara',
},
{
    nombre: 'Tequila 30-30 Añejo',
    tipo: 'tequila',
    litros: '750 ML',
    imagen: 'assets/wines/3030-Mexico-Añejo-750ml.jpg',
    precioUnitario: '9,600',
    precioCaja: '165,600',
    paisOrigen: '',
    cantidadCaja: '12',
    bodegasOrigen: 'Agroind Guadalajara',
},
]

export const catalogoLicores = [{
    nombre: 'Licor de Mango BV Land',
    tipo: 'licor',
    litros: '700 ML',
    imagen: 'assets/wines/BV-Land-Mango.jpg',
    precioUnitario: '7,800',
    precioCaja: '43,320',
    paisOrigen: '',
    cantidadCaja: '6',
    bodegasOrigen: 'Beveland, SA',
},
{
    nombre: 'Licor de Almendras BV Land',
    tipo: 'licor',
    litros: '700 ML',
    imagen: 'assets/wines/BVLand-almendras.jpg',
    precioUnitario: '7,800',
    precioCaja: '43,320',
    paisOrigen: '',
    cantidadCaja: '6',
    bodegasOrigen: 'Beveland, SA',
},
{
    nombre: 'Licor de Melocotón BV Land',
    tipo: 'licor',
    litros: '700 ML',
    imagen: 'assets/wines/BVLand-almendras.jpg',
    precioUnitario: '7,800',
    precioCaja: '43,320',
    paisOrigen: '',
    cantidadCaja: '6',
    bodegasOrigen: 'Beveland, SA',
},
{
    nombre: 'Licor de Menta Verde DISCO',
    tipo: 'licor',
    litros: '1000 ML',
    imagen: 'assets/wines/Licor-Menta-DISCO.jpg',
    precioUnitario: '5,722.50',
    precioCaja: '68,670',
    paisOrigen: '',
    cantidadCaja: '12',
    bodegasOrigen: 'Deva, SA',
},
{
    nombre: 'Licor de Manzana Verde DISCO',
    tipo: 'licor',
    litros: '1000 ML',
    imagen: 'assets/wines/Licor-de-Manzana-Disco.jpg',
    precioUnitario: '5,722.50',
    precioCaja: '68,670',
    paisOrigen: '',
    cantidadCaja: '12',
    bodegasOrigen: 'Deva, SA',
},
{
    nombre: 'Licor de Melón DISCO',
    tipo: 'licor',
    litros: '1000 ML',
    imagen: 'assets/wines/Licor-de-melon-DISCO.jpg',
    precioUnitario: '5,722.50',
    precioCaja: '68,670',
    paisOrigen: '',
    cantidadCaja: '12',
    bodegasOrigen: 'Deva, SA',
},
{
    nombre: 'Licor de Café DISCO',
    tipo: 'licor',
    litros: '1000 ML',
    imagen: 'assets/wines/Licor-de-cafe-DISCO.jpg',
    precioUnitario: '5,722.50',
    precioCaja: '68,670',
    paisOrigen: '',
    cantidadCaja: '12',
    bodegasOrigen: 'Deva, SA',
},
{
    nombre: 'Licor de Almendra DISCO',
    tipo: 'licor',
    litros: '1000 ML',
    imagen: 'assets/wines/Licor-almendra-Disco-Baja.jpg',
    precioUnitario: '5,722.50',
    precioCaja: '68,670',
    paisOrigen: '',
    cantidadCaja: '12',
    bodegasOrigen: 'Deva, SA',
},
]